### ISSUE TITLE
Orienteering course tools

### ISSUE THREAD

**Issue by Joklost** [Joklost/P8#8]
Story ID: 7, 8, 9
* Create Orienteering courses
* Add markers to map
* Hide own location from map (on app)
* Limit map edges

**Comment by MariusLauge** [comment]
https://stackoverflow.com/questions/29008384/how-to-hide-current-location-in-google-map

**Comment by MariusLauge** [comment]
https://stackoverflow.com/questions/21140754/limit-the-rectangular-area-google-maps-v2
